#include <time.h>
#include <stdio.h>
#include <stdlib.h>
#include <signal.h> //For catching SIGINTs

#include <seam.h>

#include <compiled.h> //Refs to compiled.o, generated by compilation process

//Constants
const long MAX_STEP_DURATION = 1000 / 24; //24 steps/second

//Globals
environment env;

volatile int is_running;

//Supporting functions
void _runtime_err(char* err){
	fprintf(stderr, "%s\n", err);
	exit(1);
}

void _runtime_warn(char* err){
	fprintf(stderr, "[WARN] %s\n", err);
}

void _runtime_log(char* msg){
	fprintf(stdout, "[MSG] %s\n", err);
}

void _terminate(int signal){
	is_running = 0;	
}

int main(int argc, char** argv){
	//Init SDL
	
	//Call main
	user_main(&env);
	
	//Main program loop
	is_running = 1;

	//Catch SIGINTs
	struct sigaction catcher;
	catcher.sa_handler = _terminate;
	sigemptyset(&catcher.sa_mask);
	catcher.sa_flags = SA_RESTART;
	if(sigaction(SIGINT, &catcher, NULL) > 0){
		perror("sigaction");
		return -1;
	}

	while(is_running){ //No way out besides a SIG*
		//Turn-by-turn
		long turn_start = time(NULL);

		entity* curr_entity = env.entity_head;
		while(curr_entity != NULL){
			long start = time(NULL);

			if(curr_entity->step_func != NULL) curr_entity->step_func(&env);
			
			curr_entity = curr_entity->next;
		}
		
		curr_entity = env.entity_head;
		while(curr_entity != NULL){
			long start = time(NULL);

			if(curr_entity->render_func != NULL) curr_entity->render_func(&env);
			
			curr_entity = curr_entity->next;
		}
	}

	fprintf(stdout, "Terminated by CTRL-C/SIGINT.\n");
}
