%{ open seanAst %}

%token PLUS MINUS MULTIPLY DIVIDE EOF 
%token LBRACKET RBRACKET SQLB SQRB  
%token COMMA PERIOD COLON
%token ASSIGN NOTEQUAL EQUAL
%token GT LT GTE LTE 
%token ELSE IF WHILE FOR
%token INT FLOAT
%token ENTITY MAIN TEXTURE FUNCTION

